services:
  hardware:
    build: ./hardware
    privileged: true
    restart: unless-stopped
    depends_on:
      - faces
    volumes:
      - "/dev:/dev"
      - "/sys:/sys"

  faces:
    build: ./faces
    restart: unless-stopped
    ports:
      - "5000:5000"
